# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- main: cmd/client/main.go
  binary: secureShare
  goos:
          - windows
          - linux
          - darwin
          - freebsd
          - openbsd
          - netbsd
  goarch:
          - 386
          - amd64
          - arm
          - arm64
- main: cmd/server/main.go
  binary: secureShareServer
  goos:
          - windows
          - linux
          - darwin
          - freebsd
          - openbsd
          - netbsd
  goarch:
          - 386
          - amd64
          - arm
          - arm64
- main: cmd/newUserDB/main.go
  binary: secureShareNewUserDB
  goos:
          - windows
          - linux
          - darwin
          - freebsd
          - openbsd
          - netbsd
  goarch:
          - 386
          - amd64
          - arm
          - arm64
  env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
